apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-deployment
  namespace: saleor-test
  labels:
    app: saleor-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-commerce
  template:
    metadata:
      labels:
        app: saleor-commerce
    spec:
      volumes:
      - name: saleor-media
        emptyDir: {}
      - name: saleor-redis
        emptyDir: {}
      - name: tmpfs
        emptyDir: {}
      containers:
      - name: api
        image: katieharris/saleor:v0.08
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: saleor-media
          mountPath: "/app/media"
        env:
        - name: JAEGER_AGENT_HOST
          value: localhost
        - name: DASHBOARD_URL
          value: http://saleor-service/
        - name: ALLOWED_HOSTS
          value: localhost,saleor-commerce-service
        - name: DATABASE_URL
          value: postgres://saleor:saleor@localhost:5432/saleor
        - name: CELERY_BROKER_URL
          value: redis://localhost:6379/1
        - name: DEFAULT_FROM_EMAIL
          value: noreply@example.com
        - name: EMAIL_URL
          value: smtp://localhost:1025
        - name: SECRET_KEY
          value: changeme
        - name: DEFAULT_CHANNEL_SLUG
          value: default-channel
        - name: HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS
          value: 'True'
        - name: HTTP_IP_FILTER_ENABLED
          value: 'True'
      - name: dashboard
        image: katieharris/saleor-dashboard:v0.02
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: BASE_HOST_NAME_AND_PATH/api/
      - name: db
        image: katieharris/saleor-db:v0.03
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: saleor
        - name: POSTGRES_PASSWORD
          value: saleor
      - name: redis
        image: library/redis:7.0-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: saleor-redis
          mountPath: "/data"
      - name: worker
        image: ghcr.io/saleor/saleor:3.20
        command:
        - celery
        - "-A"
        - saleor
        - "--app=saleor.celeryconf:app"
        - worker
        - "--loglevel=info"
        - "-B"
        volumeMounts:
        - name: saleor-media
          mountPath: "/app/media"
        env:
        - name: DATABASE_URL
          value: postgres://saleor:saleor@localhost:5432/saleor
        - name: CELERY_BROKER_URL
          value: redis://localhost:6379/1
        - name: DEFAULT_FROM_EMAIL
          value: noreply@example.com
        - name: EMAIL_URL
          value: smtp://localhost:1025
        - name: SECRET_KEY
          value: changeme
        - name: DEFAULT_CHANNEL_SLUG
          value: default-channel
        - name: HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS
          value: 'True'
        - name: HTTP_IP_FILTER_ENABLED
          value: 'True'
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 5775
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 14268
        - containerPort: 9411
        volumeMounts:
        - name: tmpfs
          mountPath: "/tmp"
      - name: mailpit
        image: axllent/mailpit:latest
        ports:
        - containerPort: 1025
        - containerPort: 8025
      restartPolicy: Always