apiVersion: v1
kind: Service
metadata:
  name: saleor-commerce-service
  namespace: saleor-test
spec:
  type: NodePort
  selector:
    app: saleor-commerce
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: dashboard
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: api
